In [1]:
import numpy as np

In [2]:
a=np.array([2,3,4],dtype=np.int32) #1d array
print(a)# vector
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


In [3]:
d2=np.array([[1,2,3],[1,2,3]])
print(d2) # matrix
print("           ")
d3=np.array([[[1,2],[1,2]],[[5,6],[3,5]]]) # tensor
print(d3)

[[1 2 3]
 [1 2 3]]
           
[[[1 2]
  [1 2]]

 [[5 6]
  [3 5]]]


In [4]:
np.array([1,0,3],dtype=bool)

array([ True, False,  True])

In [5]:
np.array([1,0,3],dtype=complex)

array([1.+0.j, 0.+0.j, 3.+0.j])

In [6]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
#reshape
np.arange(1,17).reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [8]:
#np.ones and zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
q=np.zeros((4,4))
print(q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
np.random.random((3,4))

array([[0.76801784, 0.56419243, 0.08451313, 0.84570744],
       [0.49841667, 0.17087713, 0.30603302, 0.86550703],
       [0.06725809, 0.80266352, 0.0391468 , 0.95859357]])

In [11]:
np.linspace(100,1,3,dtype=int) #start,end,number of

array([100,  50,   1])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
d3.ndim # no of dimensions


3

In [14]:
q.shape #tells the shape

(4, 4)

In [15]:
q.size


16

In [16]:
a.itemsize #size occuipes

4

In [17]:
print(d3.dtype)

int64


In [19]:
d3.astype(np.int8)

array([[[1, 2],
        [1, 2]],

       [[5, 6],
        [3, 5]]], dtype=int8)

In [45]:
arr1= np.arange(1,21)
arr1=arr1.reshape(4,5)
arr2=np.random.random((4,5))


In [46]:
#sacalar operations

arr1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [47]:
#relational
arr1>5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [61]:
#vector operations
new=arr1+arr2
new=np.round(new*100)
new

array([[ 172.,  228.,  331.,  420.,  524.],
       [ 693.,  710.,  859.,  988., 1070.],
       [1181., 1217., 1317., 1487., 1518.],
       [1617., 1767., 1832., 1973., 2014.]])

In [57]:
#realtional
arr1>arr2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [62]:
np.max(new)

2014.0

In [63]:
np.min(new)

172.0

In [64]:
np.sum(new)

21918.0

In [65]:
np.prod(new)

1.134396598493352e+59

In [73]:
#0->col
#1->row
new = new.astype(int)
np.max(new,axis=1)

array([ 524, 1070, 1518, 2014])

In [74]:
np.min(new,axis=0)

array([172, 228, 331, 420, 524])

In [78]:
np.prod(new,axis=1)


array([    2856747559680,   446812659493200,  4272764836666194,
       20799772757373456])

In [79]:
#mean we can do row wise and col wise also
np.mean(new)


1095.9

In [80]:
np.var(new)

331670.09

In [95]:
new=np.arange(12)
new=new.reshape(3,4)

In [96]:
new1=np.arange(12,24).reshape(4,3)

In [97]:
#dot product
np.dot(new,new1)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [101]:
#log and exp
np.exp(new1)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [102]:
np.log(new1)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [109]:
#round/floor/ceil
np.floor(np.random.random((2,3))*100)

array([[33., 42., 70.],
       [16.,  9., 17.]])

In [112]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [113]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
a2[1,0] #indexing of matrix 2d

4

In [117]:
a3[1,0,1] #indexing of tensor 3d

5

In [119]:
print(a3[0,0,0])
print(a3[1,1,0])


0
6


In [120]:
#slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
a1[2:5]

array([2, 3, 4])

In [124]:
a2[0]

array([0, 1, 2, 3])

In [125]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [133]:
a2[0::2,0:4:3]

array([[ 0,  3],
       [ 8, 11]])

In [136]:
a2[0:3:2,1:4:2]

array([[ 1,  3],
       [ 9, 11]])

In [155]:
a2[1,::3]

array([4, 7])

In [162]:
a2[:2:,1::2]

array([[1, 3],
       [5, 7]])

In [163]:
a3=np.arange(27).reshape(3,3,3)

In [164]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [171]:
a3[0,1,:]

array([3, 4, 5])

In [172]:
a3[1,:,1]

array([10, 13, 16])

In [173]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [174]:
#iteartion of numpy array
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [179]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [180]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [181]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [183]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [190]:
#transpose
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [196]:
#ravel convert to 1d array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [197]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [200]:
#horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [201]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [202]:
#horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [204]:
#vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]